title: Rarotonga, Cook Islands
description: My holiday to the Rarotonga

url: http://stevenocchipinti.github.com/2016-CookIslands-Rarotonga-Blog
baseurl: ""
paginate_path: page/
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

google_analytics: "UA-58263416-1"
