title: Rarotonga, Cook Islands
description: My holiday to the Rarotonga

url: http://stevenocchipinti.github.com/
baseurl: /2016-CookIslands-Rarotonga-Blog
paginate_path: page/
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

google_analytics: "UA-38345732-5"
